name: CD to Replit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Deploy to Replit
      run: |
        git config --global user.email "hariharank@karunya.edu.in"
        git config --global user.name "hariharank14"
        git remote add replit https://username:${{ secrets.REPLIT_TOKEN }}@git.replit.com/hariharank14
        git push replit main --force
